logging:
  #日志存储地址
  file: "logs/config/ActiveMQ.log"
  config: classpath:log4j2.yml
info:
  name : "主题消息"
server:
  #端口号
  port: 8998
  tomcat:
      uri-encoding: UTF-8
  #项目名，如果不设定，默认是 /
  context-path: /MqWechart
#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.rainboz.top.rainboz_top
  mapperLocations: classpath:mapper/*.xml


---

#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://47.100.9.160:3306/activemq?characterEncoding=utf8&useSSL=false
    username: root
    password: 550320023zhb.
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource